rm(list = ls())
install.packages("quantmod")
install.packages("dplyr")
install.packages("lubridate")
install.packages("AER")
install.packages("lmtest")
install.packages("sandwich")
install.packages("car")
library(quantmod)
library(dplyr)
library(lubridate)
library(AER)
library(lmtest)
library(sandwich)
library(car)

dir.create("R", showWarnings = FALSE)
dir.create("data_clean", showWarnings = FALSE)
dir.create("data_raw", showWarnings = FALSE)
dir.create("output", showWarnings = FALSE)

source("R/01_energy.R")
source("R/02_btc_price.R")
source("R/03_controls.R")
source("R/04_mining_cost.R")
source("R/05_merge.R")
source("R/06_regression.R")